### ISSUE TITLE
Build Warning: Layout 'none' requested in feed.xml does not exist.

### ISSUE THREAD

**Issue by larryebaum** [hmfaysal/hmfaysal-omega-theme#12]
Following your basic setup for a new Jekyll site, after forking the theme and making some minimal edits to _config.yml, attempts to bring up the site locally, with 'jeckyll serve' result in error: 

     Build Warning: Layout 'none' requested in feed.xml does not exist.

**Comment by codykonior** [comment]
I get the same issue.

**Comment by kblattmann** [comment]
@larryebaum Why don't you close this issue? You've received a couple of answers that address this.

**Comment by cmattrex** [comment]
Change the `feed` layout to `null`
