### ISSUE TITLE
Build error : Operation not permitted

### ISSUE THREAD

**Issue by psbots** [hmfaysal/hmfaysal-omega-theme#13]
Unable to build. The following error is shown.

jekyll 2.4.0 | Error:  Operation not permitted - /Users/macbookpro/Desktop/dev/web/hmfaysal-omega-theme-gh-pages/_site/LICENSE

**Comment by codykonior** [comment]
I get the same issue.

**Comment by keqiJia** [comment]
I get the same issue  too  . jekII 2.5.3

**Comment by sourabhverma** [comment]
Deleting LICENSE file form root folder worked for me.

**Comment by jojees** [comment]
Remove the LICENSE file from the Jekyll root directory.Then start Jekyll.
