### ISSUE TITLE
I have problem in "Setup for Existing Jekyll site"

### ISSUE THREAD

**Issue by galaxy-wolf** [hmfaysal/hmfaysal-omega-theme#18]
in step 1 ,  i can not find floder "plugins", and in step 2 i can not find file "about.md",

**Comment by kblattmann** [comment]
1. There is no `_plugins` directory in this repository (I think he means `_plugins` and not `plugins`). You can look [here](http://jekyllrb.com/docs/plugins/) for info about the `_plugins` directory, and you should have one in your existing Jekyll site.
1. You should also have your own `about.md` in your existing site. If you don't either make one, or forget about it. You can copy [this one](https://raw.githubusercontent.com/hmfaysal/Jekyll-HMFAYSAL-V2-Theme/master/about.md) from another of @hmfaysal's themes.
