### ISSUE TITLE
Why I fork, but it has been master can only show the structure of the theme?

### ISSUE THREAD

**Issue by AllLuckly** [hmfaysal/hmfaysal-omega-theme#19]
Why I fork, but it has been master can only show the structure of the theme?

**Comment by kblattmann** [comment]
You'll need to rephrase your issue. I don't know what you are really asking here. My only thought is that you are asking a Git question, and not an issue related to this theme.

**Comment by AllLuckly** [comment]
Has been resolved, thanks
