### ISSUE TITLE
e……I get a error    please  help  me

### ISSUE THREAD

**Issue by jk77me** [hmfaysal/hmfaysal-omega-theme#20]
that's   Jekyll2.5.3 Error :Operation not permitted-/Users/apple/Download/blog/_site/LICENSE
I deleted this file  ，but  no way。。please***

**Comment by sourabhverma** [comment]
Deleting LICENSE file form root folder worked for me.

**Comment by indiesquidge** [comment]
I get the same error for the `LICENSE` file when I try and build/serve
```sh
jekyll 2.5.3 | Error:  Operation not permitted @ unlink_internal
```
Deleting the file fixes the error, and it appears to be running locally, however a visit to the browser shows the site with zero styling. Console logs are showing that none of the assets or images can be found. Haven't run into this issue with a Jekyll template before. Then again, I haven't run into the `LICENSE` issue before either. Not really sure what to do now.
