### ISSUE TITLE
How to truncate blog post written in Chinese 

### ISSUE THREAD

**Issue by ruixinxu** [hmfaysal/hmfaysal-omega-theme#22]
@hmfaysal your template is really strong and beautiful, bug i met a question that my blogs are all written in Chinese, it seems the {{ post.content | strip_html | truncatewords:100 }} doesn't work for Chinese, so I got my whole blogs appear on my blog homepage, any tips to solve this would be appreciate.

**Comment by cmattrex** [comment]
This was probably fixed in: [Liquid Issue #166](https://github.com/Shopify/liquid/issues/166)

There's also a helper gem: [Here](https://rubygems.org/gems/chinese_truncate/versions/1.0.0)

Also this is not directly related to the theme, so I'm closing the issue.
