### ISSUE TITLE
How can I change the Date Language ?

### ISSUE THREAD

**Issue by jhoemrs** [hmfaysal/hmfaysal-omega-theme#26]
For example: January -> Janeiro ( in portuguese ) ?

**Comment by cmattrex** [comment]
If you're calling a ruby function, then it's tied to the runtime locale.

If you're talking about content specific to your website, then you'll need a localization plugin.

**Comment by jhoemrs** [comment]
I'm speak language like Portuguese, spanish, english... The dates are in English, how to translate these dates, is my question.
