### ISSUE TITLE
There is no master branch

### ISSUE THREAD

**Issue by SonOfLilit** [hmfaysal/hmfaysal-omega-theme#3]
The master branch is referenced in the readme under "protip", but doesn't exist in your public repo. Can you push it?

Also, just letting you know I'm using your theme at http://leanstartup.co.il

**Comment by djkeh** [comment]
@hmfaysal no master branch yet :cry:

**Comment by rhewitt22** [comment]
@hmfaysal bump :D

**Comment by codykonior** [comment]
Still no master branch.

**Comment by mayavanand** [comment]
@hmfaysal could you please push the master branch?

**Comment by cmattrex** [comment]
Fixed in #31
